apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-backend
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: simon34280@simonlucido.com
    privateKeySecretRef:
      name: letsencrypt-prod-backend-key
    solvers:
      - http01:
          ingress:
            class: nginx