name: Deploy frontend

on:
  repository_dispatch:
    types: [deploy-frontend]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Decode kubeconfig file
      run: |
        echo "::set-output name=KUBECONFIG_DECODED::$('${{ secrets.KUBERNETES_CONFIG }}' | base64 --decode )"
      id: kubeconfig

    - name: Install helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Move kubeconfig file
      run: echo "${{ secrets.KUBERNETES_CONFIG_DECODED }}" > ./kubeconfig

    - name: Execute helm command
      run: helm upgrade polycode-frontend ./polycode-frontend --install --kubeconfig=./kubeconfig